variables:
    ascName: oryxSP
    acrName: oryxdevmcr.azurecr.io
    skipComponentGovernanceDetection: true
    Packaging.EnableSBOMSigning: true

jobs:
- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build DotNetCore runtime stretch based images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: dotnetcore
    imageDebianFlavor: stretch
    artifactsFileName: dotnetcore-runtimeimage-bases-stretch.txt
    jobName: Build_DotNetCore_BaseImage_Stretch

- template: ../templates/_buildimageBasesJobTemplate.yml
  parameters:
    displayName: Build DotNetCore runtime buster base images
    scriptPath: ./build/buildRunTimeImageBases.sh
    imageDir: dotnetcore
    imageDebianFlavor: buster
    artifactsFileName: dotnetcore-runtimeimage-bases-buster.txt
    jobName: Build_DotNetCore_BaseImage_Buster

- job: Release_DotNetCoreRuntimeBaseImage
  dependsOn: 
    - Build_DotNetCore_BaseImage_Stretch
    - Build_DotNetCore_BaseImage_Buster
  displayName: Push images to MCR
  timeoutInMinutes: 250
  pool:
    name: AzurePipelines-EO
    demands:
      - ImageOverride -equals AzurePipelinesUbuntu20.04compliant
  steps:
    - template: ../templates/_releaseBaseImagesStepTemplate.yml
      parameters:
        baseImageName: 'dotnetcore'